### ISSUE TITLE
README files

### ISSUE THREAD

**Issue by tdiprima** [SBU-BMI/nscale#2]
Question &mdash; If a user came along and wanted to install this code, which Readme would they follow?

- [README.txt](https://github.com/SBU-BMI/nscale/blob/master/README.txt) &ndash; **Note:** the first line says "this is not up to date" &ndash; should we update it or remove it?  Do the Word documents replace it?
- [README.segment](https://github.com/SBU-BMI/nscale/blob/master/README.segment) &ndash; **Question:** Does this still apply?
- **Word docs** (for [Linux](https://github.com/SBU-BMI/nscale/blob/master/INSTALL_AND_COMPILE_nscale_library_in_Linux.docx) & [Windows](https://github.com/SBU-BMI/nscale/blob/master/INSTALL_AND_COMPILE_nscale_library_in_Windows.docx))

Thanks!

**Comment by georgeteodoro** [comment]
Hi Tammy,

The doc documents are the ones that should be used. In case you want to remove the others or transfer the information from the docs to them, you may do it.

Thanks,
George
