### ISSUE TITLE
including gpu

### ISSUE THREAD

**Issue by tdiprima** [SBU-BMI/nscale#6]
George, I have a question.  In some files we check for the with_cuda flag, and others we don't. 
 I'm guessing that if (for example) you're compiling with the intention to use with adios, cuda flag is automatically set to on (that's just a guess).

Just as a safety thing... should I go through these and make sure we're checking for that flag?  And if we're not, I can surround with if-endif...?

Please advise.  Thanks!

```
#ifdef WITH_CUDA
#include "opencv2/gpu/gpu.hpp"
#endif 
```

**Comment by georgeteodoro** [comment]
Hi Tammy,

The opencv already does the safety check. If GPU is not enabled, it creates
"empty" versions of the GPU functions that return an error code. So, in
practice it does not make difference for us to protect or not the includes.

George

2017-05-23 11:39 GMT-03:00 Tammy DiPrima <notifications@github.com>:

**Comment by tdiprima** [comment]
Thanks!
